name: First pull request

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: 'Thank you for contributing to RunelitePlus! Please make sure to join our [Discord](https://discord.gg/Q7wFtCe) and link your GitHub account to your discord account by sending `!ghauth` to our bot.'